# Naziv Aplikacije
spring.application.name=events
#paths.baseResourcePath=src/main/resources/
# Konfiguracija fajloga
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

app.elasticsearch.host=${APP_ELASTICSEARCH_HOST:localhost}
app.elasticsearch.port=${APP_ELASTICSEARCH_PORT:9200}
app.elasticsearch.scheme=${APP_ELASTICSEARCH_SCHEME:http}
app.elasticsearch.index-name=${APP_ELASTICSEARCH_INDEX_NAME:locations}

app.minio.url=${APP_MINIO_URL:http://localhost:9000}
app.minio.access-key=${APP_MINIO_ACCESS_KEY:minioadmin}
app.minio.secret-key=${APP_MINIO_SECRET_KEY:minioadmin}
app.minio.bucket.images=${APP_MINIO_BUCKET_IMAGES:images}
app.minio.bucket.documents=${APP_MINIO_BUCKET_DOCUMENTS:documents}

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin
# Konfiguracija baze podataka
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/events?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Belgrade
spring.datasource.username=root
spring.datasource.password=root
# JPA / Hibernate konfiguracija
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_HOLD
# Logging konfiguracija
logging.level.org.hibernate.SQL=off
spring.jpa.show-sql=false
# Konfiguracija mejlova
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=svtevents555@gmail.com
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Ostalo
spring.main.allow-circular-references=true
